apply plugin: 'com.android.application'

android {

    defaultConfig {
        applicationId "com.pocketbooks"
        minSdkVersion 21
        targetSdkVersion 34
        compileSdkVersion 34
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    dependencies {
        def appcompat_version = "1.6.1"
        def room_version = "2.7.0"

        implementation "androidx.appcompat:appcompat:$appcompat_version"
        implementation "androidx.appcompat:appcompat-resources:$appcompat_version"
        implementation "androidx.core:core-splashscreen:1.0.1"

        implementation "androidx.room:room-runtime:$room_version"
        annotationProcessor "androidx.room:room-compiler:$room_version"
    }
    namespace 'com.pocketbooks'
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.12.0'
}
